# This environment installs the latests released version of hydromt-sfincs,
# including some dependencies to run the examples
name: hydromt-sfincs-test

channels:
  - conda-forge

dependencies:
  - cartopy>=0.20                 # to run examples
  - descartes                     # to run examples
  - ffmpeg                        # to run examples (animation)
  # - git
  - jupyterlab                    # to run examples
  - matplotlib                    # to run examples
  - python=3.11                   # fixing python version for binder
  - pip                           # ensure pip itself is installed
  - pip:
    - hydromt-sfincs==2.0.0rc1
