name: Tests with HydroMT dev

on:
  # trigger weekly on monday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [main]
    paths:
      - tests/*
      - hydromt_sfincs/*
      - pyproject.toml
  pull_request:
    branches: [main]
    paths:
      - tests/*
      - hydromt_sfincs/*
      - pyproject.toml


jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        id: py311
        with:
          python-version: 3.11
          # caching, see https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      # true if cache-hit occurred on the primary key
      - name: Cache hit
        run: echo '${{ steps.py311.outputs.cache-hit }}'

      # build environment with pip
      - name: Install hydromt-sfincs
        run: |
          pip install --upgrade pip
          pip install .[test,examples]
          pip install git+https://github.com/Deltares/hydromt.git

      # run test
      - name: Test
        run: |
          export NUMBA_DISABLE_JIT=1
          python -m pytest --verbose
