name: Tests Dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: HydroMT dev - ubuntu-latest - py3.10
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          environment-file: envs/hydromt-sfincs-dev.yml
          activate-environment: hydromt-sfincs-dev

      - name: Conda info
        run: |
         conda info
         conda list

      - name: Intall hydromt core dev version
        run: pip install git+https://github.com/Deltares/hydromt.git

      - name: Intall hydromt_sfincs
        run: pip install .

      - name: Test
        run: python -m pytest --verbose --cov=hydromt_sfincs --cov-report xml

      - name: Check style
        run: black --check .

      - uses: codecov/codecov-action@v3
